// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBrowser():Promise<string>;

export function GetChromePath():Promise<string>;

export function GetCookie():Promise<string>;

export function SetChromePath(arg1:string):Promise<string>;
