// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBrowser() {
  return window['go']['main']['App']['CreateBrowser']();
}

export function GetCookie() {
  return window['go']['main']['App']['GetCookie']();
}
